In [61]:
import numpy as np
import random

# Q1- construct 1d numpy array, 2d numpy array,3d numpy array.

In [48]:
# 1D array
D_array = np.array([5,4,0,2,1,30])
print(D_array)
# 2D array
DD_array = np.array([[4,5,6,7,8],[1,2,3,4,5]])
print(DD_array)
# 3D array
DDD_array = np.array([[4,5,6,7,8],[1,2,3,4,5],[3,5,9,12,43]])
print(DDD_array)

[ 5  4  0  2  1 30]
[[4 5 6 7 8]
 [1 2 3 4 5]]
[[ 4  5  6  7  8]
 [ 1  2  3  4  5]
 [ 3  5  9 12 43]]


# Q2- Write a NumPy program to test whether any of the elements of a given array is non-zero. Hint use any()

In [44]:
for i in D_array:
    if i == 0:
        x = any(D_array)
        print(x)
    else:
        print("non zero")

non zero
non zero
True
non zero
non zero
non zero


# Write a NumPy program to create an array of 10 zeros, 10 ones, 10 fives.

In [47]:
z = np.ones(10)
y = np.zeros(10)
a = np.ones(10)*5
arr = np.concatenate((z, y,a))
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

# Q4- Write a NumPy program to create an array of 10 zeros 3d


In [50]:
three_arr = np.array([np.ones(10),np.ones(10),np.ones(10)])
three_arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# Q5- Write a NumPy program to create an array of the integers from 30 to 70.

In [51]:
z = np.arange(30,71)
z

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

# Q6- Write a NumPy program to create a 3x3 identity matrix.

In [54]:
z = np.identity(3)
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Q7- Write a NumPy program to generate a random number between 0 and 1.

In [62]:
z = random.randrange(0,1)
z

0

# Q8- Write a NumPy program to create a 3X4 array using and iterate over it.

In [66]:
z = np.arange(20,32).reshape(3,4)
z

array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

# Q9- Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0

In [77]:
z = np.ones((10,10))
z[1:-1,1:-1] = 0
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])